# Generated by Django 3.1.6 on 2021-02-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20210211_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='ate_uploaded',
            new_name='date_uploaded',
        ),
    ]
